### PR TITLE
Update all views to support Pancake v4.11.22 and switch from Grunt to Gulp

### PR DESCRIPTION
**Pull request by corygibbons**

### CODE REVIEW

**Comment by pocketarc** [comment]
Awesome-looking update! How're things going with Batter? Are you using it for any theme?

**Comment by corygibbons** [comment]
@BrunoDeBarros Going good thanks! Still have a little ways to go though.
As for a theme, I'm planning on using it. Playing with the idea of combining the 3 year outdated Kyou with my semi-updated personal theme and open sourcing it, but we'll see.

**Comment by pocketarc** [comment]
Have you considered putting it in the Pancake Store as well? That way they'd be able to grab it, install it and keep it up to date quite a bit more easily than if it was confined to a repo.

If you need any help with anything or any functionality in the core, just let me know! :)

**Comment by corygibbons** [comment]
Would definitely do that!

**Pull request merged**
